version: "3.9"
    
services:
   php:
     image: wiliehidayat87/php-test:latest
     ports:
      - 80:80
     restart: always
     deploy:
      replicas: 1
      mode: replicated
     volumes:
      - /Users/wiliewahyuhidayat/Documents/PHP/php-test/logs:/var/log/nginx
