name: CI

on: 
    push:
        branches: ["main"]
        tags: 
            - 'v*'
jobs:
    build-and-push-image:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                include:
                    - 
                        dockerfile: Dockerfile
                        image: wiliehidayat87/php-test
                        
        permissions:
            contents: read
            packages: write

        steps:
        -
            name: Checkout
            uses: actions/checkout@v4

        -
            name: Docker meta
            id: meta
            uses: docker/metadata-action@v5
            with:
                images: ${{ matrix.image }}
                tags: |
                    type=raw,value=latest,enable={{is_default_branch}}
        -
            name: Set up QEMU
            uses: docker/setup-qemu-action@v3
            
        -
            name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v3

        -
            name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
        -
            name: Build and push
            uses: docker/build-push-action@v5
            with:
                context: .
                platforms: linux/amd64,linux/arm64
                file: ${{ matrix.dockerfile }}
                push: true
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}